// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"lab3/server/plants"
)

// Injectors from modules.go:

func ComposeApiServer(port HttpPortNumber) (*PlantApiServer, error) {
	db, err := NewDbConnection()
	if err != nil {
		return nil, err
	}
	store := plants.NewStore(db)
	httpHandlerFunc := plants.HttpHandler(store)
	plantApiServer := &PlantApiServer{
		Port:          port,
		PlantsHandler: httpHandlerFunc,
	}
	return plantApiServer, nil
}
